name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: macos-latest
            arch: amd64
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: arm64

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo apt-get install -y cmake g++
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install cmake
        fi

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make

    - name: Package binary
      run: |
        mkdir package
        mv build/Ordering package/
        cp example_data/order_info.txt package/
        cp example_data/dish_info.txt package/

    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-binary
        path: ./package/*

  package-source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Package source
      run: |
        cd build
        sudo cpack --config CPackSourceConfig.cmake
        sudo mv package/Ordering-*-Source.tar.gz ..

    - name: Upload source artifact
      uses: actions/upload-artifact@v3
      with:
        name: source-package
        path: ./*.tar.gz

  release:
    needs: [build, package-source]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload ubuntu-latest-amd64-binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/ubuntu-latest-amd64-binary/Ordering
        asset_name: ubuntu-latest-amd64-binary
        asset_content_type: application/octet-stream

    - name: Upload ubuntu-latest-arm64-binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/ubuntu-latest-arm64-binary/Ordering
        asset_name: ubuntu-latest-arm64-binary
        asset_content_type: application/octet-stream

    - name: Upload macos-latest-amd64-binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/macos-latest-amd64-binary/Ordering
        asset_name: macos-latest-amd64-binary
        asset_content_type: application/octet-stream

    - name: Upload macos-latest-arm64-binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/macos-latest-arm64-binary/Ordering
        asset_name: macos-latest-arm64-binary
        asset_content_type: application/octet-stream

    - name: Upload source-package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/source-package/*.tar.gz
        asset_name: source-package.tar.gz
        asset_content_type: application/gzip