name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: macos-latest
            arch: amd64
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: arm64

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo apt-get install -y cmake
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install cmake
        fi

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Install
      run: sudo cmake --install build --prefix install

    - name: Package
      run: |
        sudo cpack --config build/CPackConfig.cmake
        sudo mv build/package/*.tar.gz .

    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-binary
        path: ./Ordering-*.tar.gz

    - name: Package source
      run: sudo cpack --config build/CPackSourceConfig.cmake

    - name: Upload source artifact
      uses: actions/upload-artifact@v3
      with:
        name: source-package
        path: ./Ordering-*-Source.tar.gz

  build-source:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build

    - name: Package source
      run: cpack --config build/CPackSourceConfig.cmake

    - name: Upload source artifact
      uses: actions/upload-artifact@v3
      with:
        name: source-package
        path: ./*.tar.gz