name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Install
      run: sudo cmake --install build --prefix install

    - name: Package
      run: cpack --config CPackSourceConfig.cmake

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-package
        path: ./*.tar.gz

  build-source:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package source
      run: cpack --config CPackSourceConfig.cmake

    - name: Upload source artifact
      uses: actions/upload-artifact@v2
      with:
        name: source-package
        path: ./*.tar.gz