name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: macos-latest
            arch: amd64
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: arm64

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo apt-get install -y cmake g++
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install cmake
        fi

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make

    - name: Package binary
      run: |
        mkdir package
        mv build/Ordering package/
        cp example_data/order_info.txt package/
        cp example_data/dish_info.txt package/

    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-binary
        path: ./package/*

    - name: Package source
      run: |
        cd build
        sudo cpack --config CPackSourceConfig.cmake

    - name: Upload source artifact
      uses: actions/upload-artifact@v3
      with:
        name: source-package
        path: ./build/Ordering-*-Source.tar.gz